#!/usr/bin/env python

import argparse
from glob import glob
import pandas as pd
import flammkuchen as fk
from tqdm import tqdm

parser = argparse.ArgumentParser(
    description="Rank planet candidates by SDE from TLS."
)
parser.add_argument("indir", type=str)
args = parser.parse_args()

indir = args.indir
files = glob(indir + "/*.h5")
assert len(files) > 0, "no *.h5 files found!"

# print(files)
sdes = {}
for file in tqdm(files):
    try:
        data = fk.load(file)
        sdes[file] = data["SDE"]
    except Exception as e:
        print(e)

# sort by sde
s = pd.Series(sdes, name="sde").sort_values(ascending=False)
fp = indir + "_sde.txt"
s.to_csv(fp)
print(f"Saved: {fp}")
