#!/usr/bin/env python

import deepdish as dd
from glob import glob
import pandas as pd
from tqdm import tqdm
import argparse

parser = argparse.ArgumentParser(description="Rank rotation signal by Lomb-Scargle power from GLS.")
parser.add_argument("indir", type=str)
args = parser.parse_args()

indir = args.indir
files = glob(indir + "/*.h5")
assert len(files) > 0, "no *.h5 files found!"

# print(files)
sdes = {}
for file in tqdm(files):
    try:
        data = dd.io.load(file)
        sdes[file] = data["power_gls"]
    except Exception as e:
        print(e)

# sort by sde
s = pd.Series(sdes, name="gls_power").sort_values(ascending=False)
fp = indir + "_gls.txt"
s.to_csv(fp)
print(f"Saved: {fp}")
